### ISSUE TITLE
Maybe think about publishing ESLint config

### ISSUE THREAD

**Issue by efoken** [airbnb/lunar#155]
Hi, I use the ESLint config from Lunar as a base for all my React/TypeScript projects, so how about publishing it as a package?

The `eslint-config-airbnb` is really great and is used by so much people out there, but when you start using TypeScript, you always find yourself overriding everything... I know there is this project: https://github.com/iamturns/eslint-config-airbnb-typescript, but Lunars config is so much more - so why not make it official? 😄

**Comment by milesj** [comment]
@efoken Our configs can be found in Nimbus: https://github.com/airbnb/nimbus/
