### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by milesj** [airbnb/lunar#240]
### Breaking
- [x] Remove context from translation phrases.
- [x] Remove deprecated APIs.
- [x] Remove `compact` from forms.
- [x] Rename `Props` to `<CompName>Props` (same for `State`).
- [x] Rewrite `Card` for better customization.
- [x] Migrate remaining `withStyles` to `useStyles` (unless component cannot be changed from a class). Any APIs that relied on `extendStyles` should now accept a `styleSheet` prop.
- [x] Migrate all HOCs to hooks.
- [x] Migrate some to function components.
- [x] Add `textProps` to `Link` and other components that may need it.

### New
- [x] Add generics to `Tabs` (for list of acceptable keys).

**Comment by stefhatcher** [comment]
- For `CheckBox` and `RadioButton`, default to top align instead of middle align
  - [ ] remove `topAlign` support
  - [ ] add `centerAlign` support
