### ISSUE TITLE
Autocomplete component issues

### ISSUE THREAD

**Issue by mmontag** [airbnb/lunar#26]
1. It seems that `loadItemsOnMount` implies `autoFocus`. This leads to some undesirable behavior if, for example, you apply this to multiple Autocomplete components on the same page.

2. Autocomplete component does not fire `onLoadOptions` callback for empty string input. (The only time `onLoadOptions` is fired for an empty string is when `loadItemsOnMount` is `true`.)

3. The built-in caching 5 minutes of autocomplete items cannot be disabled or configured.

The combination of issue 2 and 3 leads to some other edge cases.

Finally, just a side remark, the naming seems a bit inconsistent, as in `loadItemsOnMount` vs. `onLoadOptions`. Could be more clear if this was **items** everywhere.

**Comment by mmontag** [comment]
cc @amisha-patel

**Comment by milesj** [comment]
@mmontag 

1) This is intended. It would be weird to display the autocomplete as "open" if you're not focused on it. Native selects don't work that way.

2) This is a bug, will fix.

3) Will add a prop to bypass cache.

**Comment by mmontag** [comment]
Ok, thanks. I was confused about the purpose of `loadItemsOnMount`. Thought it was just concerned with preloading items.

**Comment by williaster** [comment]
@milesj we are also facing the issue described by `#1`. We want to pre-fetch the `Autocomplete` options for an empty query so that they display _immediately_ upon focus, which I feel like is a valid use-case

Can I fix this / add an option to opt-out of this behavior?

**Comment by williaster** [comment]
Actually I think we aren't even that concerned about the pre-fetching, we would be happy if we just had a way to fetch items _on focus_ (to populate a set of popular options) instead of requiring the user to enter something

**Comment by mmontag** [comment]
Echoing @williaster— our current solution is to tell users to type a single space to force the list of all options to show up.

**Comment by milesj** [comment]
@mmontag 

This is an alternative for 1: https://github.com/airbnb/lunar/pull/85
This should fix 3: https://github.com/airbnb/lunar/pull/91

The 2nd item won't be fixed as it's quite a behavior change in the component. Can use `loadItemsOnFocus` for possible empty string logic.

**Comment by mmontag** [comment]
Thanks @milesj, I'll try this out soon.

**Comment by milesj** [comment]
V2 landed which included some fixes. Gonna close this for now. If there are other issues, feel free to open another issue.
