### ISSUE TITLE
Layout should have a `center` prop

### ISSUE THREAD

**Issue by kesne** [airbnb/lunar#267]
Right now non-fluid layouts have a max width, but there's no way to center the layouts on the screen. There should be a `center` prop on the layout that adds `margin: auto` on the container so that it is visually centered. 

@stefhatcher

**Comment by stefhatcher** [comment]
thank you! it's released here https://github.com/airbnb/lunar/releases/tag/@airbnb/lunar-layouts@2.7.0

`centerAlign` is now available!
