### ISSUE TITLE
Need Modal support maskClosable prop

### ISSUE THREAD

**Issue by moyus** [airbnb/lunar#273]
Users may close modal by mistake when they accidentally click outside the modal and lose all the form states in the modal.

We need a `maskClosable` prop for Modal to control whether nor not auto close modal when click outside the modal.

**Comment by stefhatcher** [comment]
thank you! a `persistOnOutsideClick` prop has been added in lunar 2.54.0

ref https://github.com/airbnb/lunar/pull/276
