### ISSUE TITLE
Uncaught Error: Aesthetic has not been initialized.

### ISSUE THREAD

**Issue by Tylerian** [airbnb/lunar#28]
I've set up a minimal test project to give this library a try but I can't seem to get it working. It's always throwing out the following error: 

> Uncaught Error: Aesthetic has not been initialized. Please call `Core.initialize()` from `@airbnb/lunar`.

Here is my test file.
```
import React from 'react'
import ReactDOM from 'react-dom'

import Core from '@airbnb/lunar';

const log = (...args: object[]) => console.log(...args);

Core.initialize({
  logger: log,
  name: 'TestLunar',
});

import { Button } from '@airbnb/lunar/lib/components/Button';

ReactDOM.render(
    <Button>Test Button</Button>,
    document.getElementById('react-root')
)
```

- Any tips on getting this to work?
- Is this library intended for third-party use?

I'm using parceljs as bundler for this project if it matters.

**Comment by milesj** [comment]
> Is this library intended for third-party use?

Is it not.

However, `import`s get hoisted to the top, so your code example is not accurate. Initialize needs to happen *before* any component is imported.
