### ISSUE TITLE
OT: source maps exposed on airbnb.io

### ISSUE THREAD

**Issue by dandv** [airbnb/lunar#372]
Apologies for the OT bug. I chose this repo because I couldn't find one for the website, this one had recent activity, and not a lot of people would be spammed by the bug.

The issue is that the source code for the site is clearly visible due to Gatsby generating source maps for production builds by default. For example, comments like the one in the screenshot below are visible.

Was it intended to have the source maps exposed in production?

![image](https://user-images.githubusercontent.com/33569/81372649-07f28680-914f-11ea-82d4-ab8f408f3310.png)

**Comment by milesj** [comment]
Looping in others @lencioni

**Comment by lencioni** [comment]
Thanks for the report. My first thought is that this is probably just fine, but I'll look into it more deeply. I'll close this issue out and handle this internally.
