### ISSUE TITLE
OT: Airbnb reviews collapse whitespace

### ISSUE THREAD

**Issue by dandv** [airbnb/lunar#378]
@milesj @lencioni Thanks for looking into that issue I reported a while back. There's a more serious one I wish to report, after [the official channels didn't work out](https://twitter.com/dandv/status/1177433124470435840).

The issue is that reviews are entered and displayed in sanitized HTML, but with whitespace preserved verbatim, instead of being replaced with `&nbsp;` and `<br />`s. This causes consecutive whitespace to collapse into one, rendering carefully-formatted reviews as walls of text.

Here's an [example of a review](https://www.airbnb.com/rooms/26668211?) where the author took time to format it intelligibly, which looks very hard to read on the site:

![image](https://user-images.githubusercontent.com/33569/83365732-4ac70900-a35f-11ea-92ff-82cd6ca9a923.png)

**Comment by lencioni** [comment]
Thanks, I'll file an internal bug report

**Comment by dandv** [comment]
Hi @lencioni,

Wanted to report another bug (notifications impossible to dismiss), and thought I'd check on this issue first. The link in my OP is gone, but I still see the issue [here](https://www.airbnb.com/rooms/24475376).

**Comment by lencioni** [comment]
@dandv are you referring to the notifications here? https://www.airbnb.com/alerts

**Comment by lencioni** [comment]
The bug I filed for your original issue has been triaged but it is still open.

**Comment by lencioni** [comment]
I think this has been fixed now. Thanks for the report (and for your patience)!

![image](https://user-images.githubusercontent.com/195534/124157089-ff999100-da5d-11eb-94f7-3b59fd91ab6b.png)
